language: generic
sudo: true

services:
  - docker

jobs:
  include:
  - stage: push
    if: branch = travis-deploy
    addons:
      ssh_known_hosts: beta.aptible.com
    before_script:
      - mkdir -p ~/.ssh
      # to save it, cat <<KEY>> | base64 and save that in secrets
      - echo "$DEMO_APP_APTIBLE_GIT_SSH_KEY" | base64 -d > ~/.ssh/id_rsa
      - chmod 0400 ~/.ssh/id_rsa
      - eval "$(ssh-agent -s)"
      - ssh-add ~/.ssh/id_rsa
      - ssh-keyscan beta.aptible.com >> ~/.ssh/known_hosts

    script:
      - git remote add aptible git@beta.aptible.com:$DEMO_APP_APTIBLE_ENVIRONMENT/$DEMO_APP_APTIBLE_APP.git
      - git push aptible $TRAVIS_COMMIT:master