version: "3.3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
  deploy-demo-server:
    build:
      dockerfile: ./Dockerfile
      context: .
    entrypoint: /scripts/server-entrypoint.sh
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ./scripts:/scripts
      - ./app:/app
  deploy-demo-worker:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: python -m worker
    depends_on:
      - deploy-demo-server
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ./app:/app