version: 2.1

jobs:
  git-deploy:
    docker:
      - image: debian:latest
    filters:
      branches:
        only:
          - circle-deploy
    steps:
      # see this and add it - https://circleci.com/docs/2.0/configuration-reference/#add-ssh-keys
      - checkout
      - run:
          name: Git push and deploy to Aptible
          command: |
            apt-get update && apt-get install -y git openssh-client
            ssh-keyscan beta.aptible.com >> ~/.ssh/known_hosts
            git remote add aptible git@beta.aptible.com:$APTIBLE_ENVIRONMENT/$APTIBLE_APP.git
            git push aptible $CIRCLE_SHA1:master

workflows:
  version: 2
  deploy:
    jobs:
      - git-deploy