on:
  push:
    branches: [ main ]
  release:
    types:
      - created

env:
  DEMO_APP_APTIBLE_ENVIRONMENT: ${{ secrets.DEMO_APP_APTIBLE_ENVIRONMENT }}
  DEMO_APP_APTIBLE_APP: ${{ secrets.DEMO_APP_APTIBLE_APP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMO_APP_APTIBLE_GIT_SSH_KEY }}
      - name: Deploy to Aptible
        run: |
          git remote add aptible git@beta.aptible.com:${DEMO_APP_APTIBLE_ENVIRONMENT}/${DEMO_APP_APTIBLE_APP}.git
          git push aptible master:${GITHUB_SHA}
